website/diggers/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from django.contrib.auth.views import PasswordResetView
from django.contrib.sitemaps.views import sitemap

from . import views
from .forms import ExtendedRegistrationForm

sitemaps = {
    'categories': views.CategoriesSitemap,
    'static': views.StaticSitemap,
    'posts': views.PostsSitemap,
}

app_name = 'diggers'
urlpatterns = [
    path('', views.PostList.as_view(), name='post_list'),
    path('category/maps/', views.MapList.as_view(), name='map_list'),
    path('tags/<str:tags>/', views.PostList.as_view(), name='list_by_tags'),
    path('category/<str:category>/', views.PostListByObject.as_view(), name='list_by_category'),
    path('author/<str:author>/', views.PostListByObject.as_view(), name='list_by_author'),

    path('posts/<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
    path('posts/new/', views.PostCreate.as_view(), name='post_create'),
    path('posts/<int:pk>/edit/', views.PostUpdate.as_view(), name='post_update'),
    path('posts/<int:pk>/delete/', views.PostDelete.as_view(), name='post_delete'),

    path('maps/new/', views.MapCreate.as_view(), name='map_create'),
    path('map/<int:pk>/', views.MapDownload.as_view(), name='map_download'),

    path('posts/<int:pk>/comment/new/', views.CommentCreate.as_view(), name='comment_create'),
    path('comment/<int:cpk>/answer/', views.CommentCreate.as_view(), name='comment_answer'),
    path('comment/<int:pk>/edit/', views.CommentUpdate.as_view(), name='comment_update'),
    path('comment/<int:pk>/delete/', views.CommentDelete.as_view(), name='comment_delete'),

    path(
        'accounts/activate/complete/',
        TemplateView.as_view(
            template_name='django_registration/activation_complete.html'
        ),
        name='registration_activation_complete',
    ),
    path(
        'accounts/activate/<str:activation_key>/',
        views.EmailActivationView.as_view(),
        name='registration_activate',
    ),
    path('accounts/register/',
         views.ExtendedRegistrationView.as_view(
             form_class=ExtendedRegistrationForm
         ),
         name='registration',
         ),
    path('accounts/login/', views.ExtendedLoginView.as_view(), name='login'),
    path(
        'accounts/password_reset/',
        PasswordResetView.as_view(
            html_email_template_name='registration/password_reset_email.html',
            email_template_name='registration/password_reset_email.txt'
        ),
        name='password_reset'
    ),
    path('accounts/profile/', views.PostListByObject.as_view(by_current_user=True), name='profile'),
    path('accounts/profile/edit/', views.ProfileEditView.as_view(), name='profile_update'),

    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

website/website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('diggers.urls')),
    path('accounts/', include('django_registration.backends.one_step.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('captcha/', include('captcha.urls')),
]

website/diggers/models.py
from django.db import models
from polymorphic.models import PolymorphicModel
from django.urls import reverse
from django.contrib.auth.models import AbstractUser
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.conf import settings

import sys
from taggit.managers import TaggableManager
from mptt.models import MPTTModel, TreeForeignKey
from PIL import Image
from io import BytesIO


class User(AbstractUser):
    avatar = models.ImageField(upload_to='avatars/', blank=True, null=True, verbose_name='Аватар')
    last_activity = models.DateTimeField(null=True, blank=True, verbose_name='Був на сайті')
    email_change_token = models.CharField(max_length=80, null=True, blank=True,
                                          verbose_name='Код підтвердження зміни e-mail')
    new_email = models.CharField(max_length=40, null=True, blank=True, verbose_name='Новий e-mail')
    email_verified = models.BooleanField(default=False, verbose_name='e-mail підтверджено')
    is_banned = models.BooleanField(default=False, verbose_name='Заблоковано')
    birth_date = models.DateField(null=True, blank=True, verbose_name='Дата народження')
    location = models.CharField(max_length=80, null=True, blank=True, verbose_name='Місцезнаходження')

    def get_absolute_url(self):
        return reverse('diggers:list_by_author', kwargs={'author': self.username})

    def save(self, *args, **kwargs):
        if self.avatar:
            try:
                img = Image.open(self.avatar)
                max_width, max_height = settings.PROFILE_AVATAR_SIZE

                if img.width > max_width or img.height > max_height:
                    output_size = settings.PROFILE_AVATAR_SIZE
                    img.thumbnail(output_size)
                    img = img.convert('RGB')

                    output = BytesIO()
                    img.save(output, format='JPEG')
                    output.seek(0)

                    self.avatar = InMemoryUploadedFile(output, 'ImageField',
                                                       f'{self.avatar.name.split(".")[0]}.jpg',
                                                       'image/jpeg', sys.getsizeof(output),
                                                       None)
            except FileNotFoundError:
                self.avatar = None

        super().save(*args, **kwargs)


class Category(models.Model):
    name = models.CharField(max_length=80, verbose_name='Назва')
    route = models.CharField(max_length=20, verbose_name='Шлях')

    def get_absolute_url(self):
        return reverse('diggers:list_by_category', kwargs={'category': self.route})

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категорія'
        verbose_name_plural = 'Категорії'


class PostAbstract(PolymorphicModel):
    title = models.CharField(max_length=120, verbose_name='Заголовок')
    author = models.ForeignKey(User, verbose_name='Автор', on_delete=models.CASCADE)
    tags = TaggableManager(blank=True, verbose_name='Тэги')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')
    modified_date = models.DateTimeField(blank=True, null=True, auto_now=True, verbose_name='Дата редагування')
    is_hidden = models.BooleanField(default=False, verbose_name='Зробити прихованим')
    category = models.ForeignKey(
        Category,
        blank=True,
        null=True,
        verbose_name='Категорія',
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Пости'
        permissions = (
            ('hidden_access', 'Доступ до прихованих постів'),
        )


class Post(PostAbstract):
    text = models.TextField(verbose_name='Текст')

    def get_absolute_url(self):
        return reverse('diggers:post_detail', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'Текстовий пост'
        verbose_name_plural = 'Текстові пости'
        permissions = (
            ('moderate_post', 'Модерація постів'),
        )


class Map(PostAbstract):
    file = models.ImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='Файл')
    description = models.TextField(blank=True, verbose_name='Опис')

    def get_absolute_url(self):
        return reverse('diggers:post_detail', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        self.is_hidden = True
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Мапа'
        verbose_name_plural = 'Мапи'
        permissions = (
            ('moderate_map', 'Модерація мап'),
        )


class Comment(MPTTModel):
    post = models.ForeignKey(PostAbstract, verbose_name='Пост', on_delete=models.CASCADE)
    author = models.ForeignKey(User, verbose_name='Автор', on_delete=models.CASCADE)
    text = models.TextField(verbose_name='Текст')
    parent = TreeForeignKey(
        'self',
        null=True,
        blank=True,
        related_name='children',
        db_index=True,
        verbose_name='Відповідь на',
        on_delete=models.CASCADE
    )
    is_deleted = models.BooleanField(default=False, verbose_name='Видалено')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')
    modified_date = models.DateTimeField(blank=True, null=True, auto_now=True, verbose_name='Дата редагування')

    def is_hidden(self):
        return self.post.is_hidden

    def __str__(self):
        return self.text[:80]

    class Meta:
        verbose_name = 'Коментар'
        verbose_name_plural = 'Коментарі'
        permissions = (
            ('moderate_comment', 'Модерація коментарів'),
        )

    class MPTTMeta:
        order_insertion_by = ['created_date']

website/diggers/forms.py
import re
from django import forms
from django_registration.forms import RegistrationForm
from django.contrib.auth.forms import AuthenticationForm
from captcha.fields import CaptchaField

from .models import User, Comment, Post, Map
from .widgets import CKEditorWidget


class PostAbstractForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.author = kwargs['initial']['author']
        super(PostAbstractForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super().clean()

        tags = cleaned_data.get('tags')

        for i, tag in enumerate(tags):
            tags[i] = re.sub(r'[^\w\s\d\-_,]', '', tag).lower()

        cleaned_data['tags'] = tags

        return cleaned_data


class AttachCurrentUserMixin(forms.ModelForm):
    def save(self, commit=True):
        obj = super(AttachCurrentUserMixin, self).save(commit=False)
        obj.author = self.author

        if commit:
            obj.save()
            self.save_m2m()

        return obj


class PostForm(PostAbstractForm):
    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['category'].empty_label = None
        self.fields['category'].required = True
        self.fields['text'].widget = CKEditorWidget()
        if not self.author.has_perm('diggers.hidden_access'):
            self.fields['is_hidden'].widget = forms.HiddenInput()

    class Meta:
        model = Post
        fields = ['title', 'text', 'category', 'tags', 'is_hidden']


class MapForm(PostAbstractForm):
    def __init__(self, *args, **kwargs):
        super(MapForm, self).__init__(*args, **kwargs)
        self.fields['description'].widget = CKEditorWidget(mode='simple')

    class Meta:
        model = Map
        fields = ['title', 'file', 'description', 'tags']


class PostCreateForm(AttachCurrentUserMixin, PostForm):
    pass


class MapCreateForm(AttachCurrentUserMixin, MapForm):
    pass


class CommentCreateForm(forms.ModelForm):
    parent = None

    class Meta:
        model = Comment
        fields = ['text']

    def __init__(self, *args, **kwargs):
        self.author = kwargs['initial']['author']
        self.post = kwargs['initial']['post']
        if 'parent' in kwargs['initial']:
            self.parent = kwargs['initial']['parent']

        super(CommentCreateForm, self).__init__(*args, **kwargs)
        self.fields['text'].widget = CKEditorWidget(mode='simple')

    def save(self, commit=True):
        obj = super(CommentCreateForm, self).save(commit=False)
        obj.author = self.author
        obj.post = self.post

        if self.parent:
            obj.parent = self.parent

        if commit:
            obj.save()
            self.save_m2m()

        return obj


class CommentUpdateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

    def __init__(self, *args, **kwargs):
        super(CommentUpdateForm, self).__init__(*args, **kwargs)
        self.fields['text'].widget = CKEditorWidget(mode='simple')


class ExtendedRegistrationForm(RegistrationForm):
    captcha = CaptchaField()

    class Meta(RegistrationForm.Meta):
        model = User
        fields = [
            User.USERNAME_FIELD,
            User.get_email_field_name(),
            "password1",
            "password2",
            "avatar",
            "birth_date",
            "location",
            "captcha"
        ]
        widgets = {
            'birth_date': forms.widgets.DateInput(attrs={'type': 'date'})
        }


class ExtendedLoginForm(AuthenticationForm):
    remember_me = forms.BooleanField(required=False, label='Запам’ятати мене')


class ProfileForm(forms.ModelForm):
    class Meta(RegistrationForm.Meta):
        model = User
        fields = ['first_name', 'last_name', 'email', 'avatar', 'birth_date', 'location']
        widgets = {
            'birth_date': forms.widgets.DateInput(attrs={'type': 'date'})
        }

website/diggers/templates/diggers/base.html
{% load static %}

<!DOCTYPE html>
<html class="no-js" lang="en">
<head>

    <!--- basic page needs
    ================================================== -->
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %} — Сайт диґерів Києва</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="referrer" content="origin">

    <!-- mobile specific metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSS
    ================================================== -->
    <link rel="stylesheet" href="{% static "css/base.css" %}">
    <link rel="stylesheet" href="{% static "css/main.css" %}">

    <!-- script
    ================================================== -->
    <script src="{% static "js/modernizr.js" %}"></script>
    <script defer src="{% static "js/fontawesome/all.min.js" %}"></script>

    <!-- favicons
    ================================================== -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "apple-touch-icon.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "favicon-32x32.png" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "favicon-16x16.png" %}">
    <link rel="manifest" href="{% static "site.webmanifest" %}">

</head>

<body id="top" {% if post %}class="ss-single"{% endif %}>

    <!-- preloader
    ================================================== -->
    <div id="preloader">
        <div id="loader" class="dots-fade">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>

    <!-- Header
    ================================================== -->
    <header class="s-header">

        <div class="row">

            <div class="s-header__content column">
                <h1 class="s-header__logotext">
                    <a href="{% url 'diggers:post_list' %}" title="">Kiyv spelestology</a>
                </h1>
                <p class="s-header__tagline">Сайт диґерів Києва</p>
            </div>

        </div> <!-- end row -->

       <nav class="s-header__nav-wrap">

           <div class="row">
               {% include "diggers/blocks/nav.html" %}
           </div>

        </nav> <!-- end #nav-wrap -->

        <a class="header-menu-toggle" href="#" title="Меню"><span>Меню</span></a>

    </header> <!-- Header End -->

    <!-- Content
    ================================================== -->
    <div class="s-content">

    {% block layout %}{% endblock %}

   </div> <!-- end content-wrap -->

    <!-- Footer
    ================================================== -->
    <footer class="s-footer">

        <div class="row s-footer__top">

            <div class="ss-copyright">
                <span>© Kiev Spelestology 2021</span>
                <span>Design by <a href="https://www.styleshout.com/">StyleShout</a></span>
            </div>

        </div> <!-- end footer__bottom -->


        <div class="ss-go-top">
            <a class="smoothscroll" title="Вгору" href="#top">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 0l8 9h-6v15h-4v-15h-6z"></path></svg>
            </a>
        </div> <!-- end ss-go-top -->

    </footer> <!-- end Footer-->


    <!-- Java Script
    ================================================== -->
    <script src="{% static "js/jquery-3.2.1.min.js" %}"></script>
    <script src="{% static "js/main.js" %}"></script>

</body>

</html>

website/diggers/templates/diggers/base_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    {% block content %}{% endblock %}
</body>
</html>

website/diggers/templates/diggers/comment_confirm_delete.html
{% extends 'diggers/layouts/page.html' %}

{% block title %}Видалення коментаря: {{ comment.text | striptags | truncatechars:40 }}{% endblock %}

{% block content %}
    <section class="page-content">

        <h2 class="page-content__title h1">Видалення коментаря: {{ comment.text | striptags | truncatechars:40 }}</h2>

        <form method="POST">
            {% csrf_token %}

            <p class="lead">
                Ви підтверджуєте видалення коментаря?
            </p>

            <p>
                <input type="submit" class="btn btn--primary" value="Видалити">
                <a class="btn btn--stroke" href="{{ view.get_success_url }}">Скасувати</a>
            </p>
        </form>
    </section> <!-- end page -->
{% endblock %}

website/diggers/templates/diggers/comment_create_form.html
{% extends 'diggers/layouts/page.html' %}

{% block title %}
    {% if parent %}
        Відповідь на коментар {{ parent.author }}
    {% else %}
        Створення коментаря
    {% endif %}
{% endblock %}

{% block content %}
    <section class="page-content">
        <h2 class="page-content__title h1">
            {% if parent %}
                Відповідь на коментар {{ parent.author }}: {{ parent.text | striptags | truncatechars:40 }}
            {% else %}
                Створення коментаря
            {% endif %}
        </h2>

        <form method="POST" enctype="multipart/form-data">
            {% include "diggers/blocks/form.html" %}
            <button type="submit" class="btn--primary h-full-width">Відправити</button>
        </form>
    </section>
{% endblock %}

website/diggers/templates/diggers/comment_update_form.html
{% extends 'diggers/layouts/page.html' %}

{% block title %}Редагування коментаря: {{ comment.text | striptags | truncatechars:40 }}{% endblock %}

{% block content %}
    <section class="page-content">
        <h2 class="page-content__title h1">Редагування коментаря: {{ comment.text | striptags | truncatechars:40 }}</h2>

        <form method="POST" enctype="multipart/form-data">
            {% include "diggers/blocks/form.html" %}
            <button type="submit" class="btn--primary h-full-width">Зберегти</button>
        </form>
    </section>
{% endblock %}

website/diggers/templates/diggers/map_confirm_delete.html
{% extends 'diggers/layouts/page.html' %}

{% block title %}Видалення мапи{% endblock %}

{% block content %}
    <section class="page-content">

        <h2 class="page-content__title h1">Видалення мапи "{{ map.title }}"</h2>

        <form method="POST">
            {% csrf_token %}

            <p class="lead">
                Ви підтверджуєте видалення мапи?
            </p>

            <p>
                <input type="submit" class="btn btn--primary" value="Видалити">
                <a class="btn btn--stroke" href="{{ view.get_success_url }}">Скасувати</a>
            </p>
        </form>
    </section> <!-- end page -->
{% endblock %}

website/diggers/templates/diggers/map_create_form.html
{% extends 'diggers/layouts/page.html' %}

{% block title %}Завантаження мапи{% endblock %}

{% block content %}
    <section class="page-content">
        <h2 class="page-content__title h1">Завантаження мапи</h2>

        <form method="POST" enctype="multipart/form-data">
            {% include "diggers/blocks/form.html" %}
            <button type="submit" class="btn--primary h-full-width">Зберегти</button>
        </form>
    </section>
{% endblock %}

website/diggers/templates/diggers/map_update_form.html
{% extends 'diggers/layouts/page.html' %}

{% block title %}Редагування мапи "{{ map.title }}"{% endblock %}

{% block content %}
    <section class="page-content">
        <h2 class="page-content__title h1">Редагування мапи "{{ map.title }}"</h2>

        <form method="POST" enctype="multipart/form-data">
            {% include "diggers/blocks/form.html" %}
            <button type="submit" class="btn--primary h-full-width">Зберегти</button>
        </form>
    </section>
{% endblock %}

website/diggers/templates/diggers/post_detail.html
{% extends 'diggers/layouts/blog.html' %}
{% load mptt_tags %}
{% load static %}
{% load plural %}
{% load bleach_post %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <article class="entry">

        <header class="entry__header">

            <h2 class="entry__title h1">
                <a href="{% url 'diggers:post_detail' post.pk %}" title="">{{ post.title }}</a>
            </h2>

            {% include "diggers/blocks/post_meta.html" %}
        </header> <!-- entry__header -->

        <div class="entry__content">
            {% if post.file %}
                <a href="{% url 'diggers:map_download' post.pk %}" target="_blank">Завантажити</a>
                <br>
                <a href="{{ MEDIA_URL }}{{ post.file }}" target="_blank">
                    <img src="{{ MEDIA_URL }}{{ post.file }}" alt="upload"/>
                </a>
                {{ post.description|bleach }}
            {% else %}
                {{ post.text|bleach }}
            {% endif %}
        </div> <!-- entry__content -->

        {% if post.tags.all %}
            <p class="entry__tags">
                <span>Tagged in </span>:
                {% for tag in post.tags.all %}
                    {% if not forloop.first %}&nbsp;{% endif %}
                    <a href="{% url 'diggers:list_by_tags' tags=tag.name %}">#{{ tag.name }}</a>
                    {% if not forloop.last %}, {% endif %}
                {% endfor %}
            </p>
        {% endif %}

        {% if next_post or prev_post %}
            <ul class="entry__post-nav h-group">
                {% if prev_post %}
                    <li class="prev"><a rel="prev" href="{% url "diggers:post_detail" prev_post.pk %}"><strong
                            class="h6">Попередній пост</strong>
                        {{ prev_post.title }}</a></li>
                {% endif %}
                {% if next_post %}
                    <li class="next"><a rel="next" href="{% url "diggers:post_detail" next_post.pk %}"><strong
                            class="h6">Наступний пост</strong>
                        {{ next_post.title }}</a></li>
                {% endif %}
            </ul>
        {% endif %}

    </article> <!-- end entry -->

    <div class="comments-wrap">

        {% with post.comment_set.all as comments %}
            <div id="comments">
                <h3>{{ comments.count }} коментар{{ comments.count | plural:',я,ів' }}</h3>

                {% if comments %}
                    <!-- START commentlist -->
                    <ol class="commentlist">
                        {% recursetree comments %}
                            <li class="{% if not node.is_leaf_node and node.level == 0 %}thread-alt{% endif %}
                        depth-{{ node.level }} comment {% if node.is_deleted %}deleted{% endif %}"
                                id="comment{{ node.pk }}">

                                {% if not node.is_deleted %}
                                    <div class="comment__avatar">
                                        {% if node.author.avatar %}
                                            <img src="{{ MEDIA_URL }}{{ node.author.avatar }}" alt="avatar"/>
                                        {% else %}
                                            <img src="{% static "images/thumb.jpg" %}" alt="avatar"/>
                                        {% endif %}
                                    </div>

                                    <div class="comment__content">

                                        <div class="comment__info">
                                            <div class="comment__author">
                                                <a href="{% url 'diggers:list_by_author' node.author.username %}">{{ node.author.username }}</a>
                                            </div>

                                            <div class="comment__meta">
                                                <div class="comment__time">{{ node.created_date }}</div>
                                                {% if request.user.is_authenticated %}
                                                    <div class="comment__reply">
                                                        <a class="comment-reply-link"
                                                           href="{% url 'diggers:comment_answer' node.pk %}">Відповідь</a>
                                                    </div>

                                                    {% if node.author == request.user %}
                                                        <div>
                                                            <a class="comment-reply-link"
                                                               href="{% url 'diggers:comment_update' node.pk %}">Редагувати</a>
                                                            <a class="comment-reply-link"
                                                               href="{% url 'diggers:comment_delete' node.pk %}">Видалити</a>
                                                        </div>
                                                    {% endif %}
                                                {% endif %}
                                            </div>
                                        </div>

                                        <div class="comment__text">
                                            {{ node.text|bleach }}
                                        </div>
                                    </div>
                                {% else %}
                                    <div class="comment__avatar"></div>
                                    <div class="comment__content">
                                        <div class="comment__info"></div>
                                        <div class="comment__text">
                                            <p>
                                                Коментар видалено
                                            </p>
                                        </div>
                                    </div>
                                {% endif %}

                                {% if not node.is_leaf_node %}
                                    <ul class="children">
                                        {{ children }}
                                    </ul>
                                {% endif %}
                            </li> <!-- end comment level {{ node.level }} -->

                        {% endrecursetree %}

                    </ol>
                    <!-- END commentlist -->
                {% endif %}

            </div> <!-- end comments -->
        {% endwith %}

        <div class="comment-respond">
            {% if form %}
                <!-- START respond -->
                <div id="respond">

                    <h3>Додати коментар</h3>

                    <form method="POST" enctype="multipart/form-data"
                          action="{% url 'diggers:comment_create' post.pk %}">
                        {% include "diggers/blocks/form.html" %}
                        <button type="submit" class="btn--primary h-full-width">Відправити</button>
                    </form>
                </div>
                <!-- END respond-->
            {% else %}
                Увійдіть або зареєструйтеся щоб залишати коментарі.
            {% endif %}
        </div> <!-- end comment-respond -->


    </div> <!-- end comments-wrap -->
{% endblock %}

website/diggers/templates/diggers/post_list.html
{% extends 'diggers/layouts/blog.html' %}
{% load static %}
{% load bleach_post %}

{% block title %}
    {% if author %}
        {% if author == request.user %}Мої пости{% else %}Пости користувача {{ author.username }}{% endif %}
    {% elif category %}
        Пости категорії {{ category.name }}
    {% elif tags %}
        Пости за тегами {{ tags }}
    {% else %}
        Блоґ
    {% endif %}
{% endblock %}

{% block content %}
    {% if author %}
        {% include 'diggers/blocks/profile.html' %}
    {% elif category %}
        <h2 class="page-content__title">Пости категорії {{ category.name }}</h2>
    {% elif tags %}
        <h2 class="page-content__title">Пости за тегами {{ tags }}</h2>
    {% endif %}

    {% for post in object_list %}
        <article class="entry">

            <header class="entry__header">

                <h2 class="entry__title h1">
                    <a href="{% url 'diggers:post_detail' post.pk %}" title="">{{ post.title }}</a>
                </h2>

                {% include "diggers/blocks/post_meta.html" %}

            </header>

            <div class="entry__content">
                {% if post.file %}
                    <a href="{% url 'diggers:map_download' post.pk %}" target="_blank">Завантажити</a>
                    <br>
                    <a href="{{ MEDIA_URL }}{{ post.file }}" target="_blank">
                        <img src="{{ MEDIA_URL }}{{ post.file }}" alt="upload"/>
                    </a>
                    {{ post.description|truncatechars_html:400|bleach }}
                {% else %}
                    {{ post.text|bleach|truncatechars_html:400 }}
                    {% if post.text|length > 400 %}
                        <a href="{% url 'diggers:post_detail' post.pk %}">Читати далі...</a>
                    {% endif %}
                {% endif %}
            </div>
        </article> <!-- end entry -->
    {% endfor %}

    {% if is_paginated %}
        <!-- page nav -->
        <nav class="pgn">
            <ul>
                {% if page_obj.has_previous %}
                    <li>
                        <a rel="prev" class="pgn__prev" href="?page={{ page_obj.previous_page_number }}">Попередня</a>
                    </li>
                {% endif %}

                {% for i in page_obj.paginator.page_range %}
                    <li>
                        {% if page_obj.number == i %}
                            <span class="pgn__num current">{{ i }}</span>
                        {% else %}
                            <a rel="page{{ i }}" class="pgn__num" href="?page={{ i }}">{{ i }}</a>
                        {% endif %}
                    </li>
                {% endfor %}

                {% if page_obj.has_next %}
                    <li>
                        <a rel="next" class="pgn__next" href="?page={{ page_obj.next_page_number }}">Наступна</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}
{% endblock %}