website/diggers/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from django.contrib.auth.views import PasswordResetView
from django.contrib.sitemaps.views import sitemap

from . import views
from .forms import ExtendedRegistrationForm

sitemaps = {
    'categories': views.CategoriesSitemap,
    'static': views.StaticSitemap,
    'posts': views.PostsSitemap,
}

app_name = 'diggers'
urlpatterns = [
    path('', views.PostList.as_view(), name='post_list'),
    path('category/maps/', views.MapList.as_view(), name='map_list'),
    path('tags/<str:tags>/', views.PostList.as_view(), name='list_by_tags'),
    path('category/<str:category>/', views.PostListByObject.as_view(), name='list_by_category'),
    path('author/<str:author>/', views.PostListByObject.as_view(), name='list_by_author'),

    path('posts/<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
    path('posts/new/', views.PostCreate.as_view(), name='post_create'),
    path('posts/<int:pk>/edit/', views.PostUpdate.as_view(), name='post_update'),
    path('posts/<int:pk>/delete/', views.PostDelete.as_view(), name='post_delete'),

    path('maps/new/', views.MapCreate.as_view(), name='map_create'),
    path('map/<int:pk>/', views.MapDownload.as_view(), name='map_download'),

    path('posts/<int:pk>/comment/new/', views.CommentCreate.as_view(), name='comment_create'),
    path('comment/<int:cpk>/answer/', views.CommentCreate.as_view(), name='comment_answer'),
    path('comment/<int:pk>/edit/', views.CommentUpdate.as_view(), name='comment_update'),
    path('comment/<int:pk>/delete/', views.CommentDelete.as_view(), name='comment_delete'),

    path(
        'accounts/activate/complete/',
        TemplateView.as_view(
            template_name='django_registration/activation_complete.html'
        ),
        name='registration_activation_complete',
    ),
    path(
        'accounts/activate/<str:activation_key>/',
        views.EmailActivationView.as_view(),
        name='registration_activate',
    ),
    path('accounts/register/',
         views.ExtendedRegistrationView.as_view(
             form_class=ExtendedRegistrationForm
         ),
         name='registration',
         ),
    path('accounts/login/', views.ExtendedLoginView.as_view(), name='login'),
    path(
        'accounts/password_reset/',
        PasswordResetView.as_view(
            html_email_template_name='registration/password_reset_email.html',
            email_template_name='registration/password_reset_email.txt'
        ),
        name='password_reset'
    ),
    path('accounts/profile/', views.PostListByObject.as_view(by_current_user=True), name='profile'),
    path('accounts/profile/edit/', views.ProfileEditView.as_view(), name='profile_update'),

    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

website/website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('diggers.urls')),
    path('accounts/', include('django_registration.backends.one_step.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('captcha/', include('captcha.urls')),
]

website/diggers/models.py
from django.db import models
from polymorphic.models import PolymorphicModel
from django.urls import reverse
from django.contrib.auth.models import AbstractUser
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.conf import settings

import sys
from taggit.managers import TaggableManager
from mptt.models import MPTTModel, TreeForeignKey
from PIL import Image
from io import BytesIO


class User(AbstractUser):
    avatar = models.ImageField(upload_to='avatars/', blank=True, null=True, verbose_name='Аватар')
    last_activity = models.DateTimeField(null=True, blank=True, verbose_name='Був на сайті')
    email_change_token = models.CharField(max_length=80, null=True, blank=True,
                                          verbose_name='Код підтвердження зміни e-mail')
    new_email = models.CharField(max_length=40, null=True, blank=True, verbose_name='Новий e-mail')
    email_verified = models.BooleanField(default=False, verbose_name='e-mail підтверджено')
    is_banned = models.BooleanField(default=False, verbose_name='Заблоковано')
    birth_date = models.DateField(null=True, blank=True, verbose_name='Дата народження')
    location = models.CharField(max_length=80, null=True, blank=True, verbose_name='Місцезнаходження')

    def get_absolute_url(self):
        return reverse('diggers:list_by_author', kwargs={'author': self.username})

    def save(self, *args, **kwargs):
        if self.avatar:
            try:
                img = Image.open(self.avatar)
                max_width, max_height = settings.PROFILE_AVATAR_SIZE

                if img.width > max_width or img.height > max_height:
                    output_size = settings.PROFILE_AVATAR_SIZE
                    img.thumbnail(output_size)
                    img = img.convert('RGB')

                    output = BytesIO()
                    img.save(output, format='JPEG')
                    output.seek(0)

                    self.avatar = InMemoryUploadedFile(output, 'ImageField',
                                                       f'{self.avatar.name.split(".")[0]}.jpg',
                                                       'image/jpeg', sys.getsizeof(output),
                                                       None)
            except FileNotFoundError:
                self.avatar = None

        super().save(*args, **kwargs)


class Category(models.Model):
    name = models.CharField(max_length=80, verbose_name='Назва')
    route = models.CharField(max_length=20, verbose_name='Шлях')

    def get_absolute_url(self):
        return reverse('diggers:list_by_category', kwargs={'category': self.route})

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категорія'
        verbose_name_plural = 'Категорії'


class PostAbstract(PolymorphicModel):
    title = models.CharField(max_length=120, verbose_name='Заголовок')
    author = models.ForeignKey(User, verbose_name='Автор', on_delete=models.CASCADE)
    tags = TaggableManager(blank=True, verbose_name='Тэги')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')
    modified_date = models.DateTimeField(blank=True, null=True, auto_now=True, verbose_name='Дата редагування')
    is_hidden = models.BooleanField(default=False, verbose_name='Зробити прихованим')
    category = models.ForeignKey(
        Category,
        blank=True,
        null=True,
        verbose_name='Категорія',
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Пости'
        permissions = (
            ('hidden_access', 'Доступ до прихованих постів'),
        )


class Post(PostAbstract):
    text = models.TextField(verbose_name='Текст')

    def get_absolute_url(self):
        return reverse('diggers:post_detail', kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'Текстовий пост'
        verbose_name_plural = 'Текстові пости'
        permissions = (
            ('moderate_post', 'Модерація постів'),
        )


class Map(PostAbstract):
    file = models.ImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='Файл')
    description = models.TextField(blank=True, verbose_name='Опис')

    def get_absolute_url(self):
        return reverse('diggers:post_detail', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        self.is_hidden = True
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Мапа'
        verbose_name_plural = 'Мапи'
        permissions = (
            ('moderate_map', 'Модерація мап'),
        )


class Comment(MPTTModel):
    post = models.ForeignKey(PostAbstract, verbose_name='Пост', on_delete=models.CASCADE)
    author = models.ForeignKey(User, verbose_name='Автор', on_delete=models.CASCADE)
    text = models.TextField(verbose_name='Текст')
    parent = TreeForeignKey(
        'self',
        null=True,
        blank=True,
        related_name='children',
        db_index=True,
        verbose_name='Відповідь на',
        on_delete=models.CASCADE
    )
    is_deleted = models.BooleanField(default=False, verbose_name='Видалено')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')
    modified_date = models.DateTimeField(blank=True, null=True, auto_now=True, verbose_name='Дата редагування')

    def is_hidden(self):
        return self.post.is_hidden

    def __str__(self):
        return self.text[:80]

    class Meta:
        verbose_name = 'Коментар'
        verbose_name_plural = 'Коментарі'
        permissions = (
            ('moderate_comment', 'Модерація коментарів'),
        )

    class MPTTMeta:
        order_insertion_by = ['created_date']

website/diggers/forms.py
import re
from django import forms
from django_registration.forms import RegistrationForm
from django.contrib.auth.forms import AuthenticationForm
from captcha.fields import CaptchaField

from .models import User, Comment, Post, Map
from .widgets import CKEditorWidget


class PostAbstractForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.author = kwargs['initial']['author']
        super(PostAbstractForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super().clean()

        tags = cleaned_data.get('tags')

        for i, tag in enumerate(tags):
            tags[i] = re.sub(r'[^\w\s\d\-_,]', '', tag).lower()

        cleaned_data['tags'] = tags

        return cleaned_data


class AttachCurrentUserMixin(forms.ModelForm):
    def save(self, commit=True):
        obj = super(AttachCurrentUserMixin, self).save(commit=False)
        obj.author = self.author

        if commit:
            obj.save()
            self.save_m2m()

        return obj


class PostForm(PostAbstractForm):
    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.fields['category'].empty_label = None
        self.fields['category'].required = True
        self.fields['text'].widget = CKEditorWidget()
        if not self.author.has_perm('diggers.hidden_access'):
            self.fields['is_hidden'].widget = forms.HiddenInput()

    class Meta:
        model = Post
        fields = ['title', 'text', 'category', 'tags', 'is_hidden']


class MapForm(PostAbstractForm):
    def __init__(self, *args, **kwargs):
        super(MapForm, self).__init__(*args, **kwargs)
        self.fields['description'].widget = CKEditorWidget(mode='simple')

    class Meta:
        model = Map
        fields = ['title', 'file', 'description', 'tags']


class PostCreateForm(AttachCurrentUserMixin, PostForm):
    pass


class MapCreateForm(AttachCurrentUserMixin, MapForm):
    pass


class CommentCreateForm(forms.ModelForm):
    parent = None

    class Meta:
        model = Comment
        fields = ['text']

    def __init__(self, *args, **kwargs):
        self.author = kwargs['initial']['author']
        self.post = kwargs['initial']['post']
        if 'parent' in kwargs['initial']:
            self.parent = kwargs['initial']['parent']

        super(CommentCreateForm, self).__init__(*args, **kwargs)
        self.fields['text'].widget = CKEditorWidget(mode='simple')

    def save(self, commit=True):
        obj = super(CommentCreateForm, self).save(commit=False)
        obj.author = self.author
        obj.post = self.post

        if self.parent:
            obj.parent = self.parent

        if commit:
            obj.save()
            self.save_m2m()

        return obj


class CommentUpdateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

    def __init__(self, *args, **kwargs):
        super(CommentUpdateForm, self).__init__(*args, **kwargs)
        self.fields['text'].widget = CKEditorWidget(mode='simple')


class ExtendedRegistrationForm(RegistrationForm):
    captcha = CaptchaField()

    class Meta(RegistrationForm.Meta):
        model = User
        fields = [
            User.USERNAME_FIELD,
            User.get_email_field_name(),
            "password1",
            "password2",
            "avatar",
            "birth_date",
            "location",
            "captcha"
        ]
        widgets = {
            'birth_date': forms.widgets.DateInput(attrs={'type': 'date'})
        }


class ExtendedLoginForm(AuthenticationForm):
    remember_me = forms.BooleanField(required=False, label='Запам’ятати мене')


class ProfileForm(forms.ModelForm):
    class Meta(RegistrationForm.Meta):
        model = User
        fields = ['first_name', 'last_name', 'email', 'avatar', 'birth_date', 'location']
        widgets = {
            'birth_date': forms.widgets.DateInput(attrs={'type': 'date'})
        }

website/diggers/templates/diggers/blocks/categories.html
{% load categories %}

<div class="widget widget--categories">
    <h3 class="h6">Категорії.</h3>
    <ul>
        {% categories as list %}
        {% for category in list %}
            <li>
                <a href="{% url 'diggers:list_by_category' category=category.route %}">{{ category }}</a>
                ({{ category.posts_count }})
            </li>
        {% endfor %}
        {% if request.user.is_authenticated and perms.diggers.hidden_access %}
            <li><a href="{% url 'diggers:map_list' %}">Мапи</a> ({% maps_count %})</li>
        {% endif %}
    </ul>
</div>

website/diggers/templates/diggers/blocks/form.html
{% load widget_tweaks %}

{% csrf_token %}
{{ form.media }}
<div>
    {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
            <div class="alert-box alert-box--error hideit">
                <p>{{ error }}</p>
                <svg class="svg-inline--fa fa-times fa-w-11 alert-box__close" aria-hidden="true" focusable="false"
                     data-prefix="fa" data-icon="times" role="img" xmlns="http://www.w3.org/2000/svg"
                     viewBox="0 0 352 512" data-fa-i2svg="">
                    <path fill="currentColor"
                          d="M242.72 256l100.07-100.07c12.28-12.28 12.28-32.19 0-44.48l-22.24-22.24c-12.28-12.28-32.19-12.28-44.48 0L176 189.28 75.93 89.21c-12.28-12.28-32.19-12.28-44.48 0L9.21 111.45c-12.28 12.28-12.28 32.19 0 44.48L109.28 256 9.21 356.07c-12.28 12.28-12.28 32.19 0 44.48l22.24 22.24c12.28 12.28 32.2 12.28 44.48 0L176 322.72l100.07 100.07c12.28 12.28 32.2 12.28 44.48 0l22.24-22.24c12.28-12.28 12.28-32.19 0-44.48L242.72 256z"></path>
                </svg><!-- <i class="fa fa-times alert-box__close" aria-hidden="true"></i> -->
            </div>
            <!-- end error -->
        {% endfor %}
    {% endif %}


    {% for hidden in form.hidden_fields %}
        {{ hidden }}
    {% endfor %}

    {% for field in form.visible_fields %}
        <div{% if forloop.last %} class="h-add-bottom"{% endif %}>
            {% if field|widget_type == 'select' %}
                <label for="{{ field.id_for_label }}">
                    {{ field.label }}{% if field.field.required %}*{% endif %}
                </label>
                <div class="ss-custom-select">
                    {% render_field field|add_class:"h-full-width" %}
                </div>
            {% elif field|widget_type == 'checkboxinput' %}
                <div>
                    <label for="{{ field.id_for_label }}">
                        {{ field }}
                        <span class="label-text">{{ field.label }}{% if field.field.required %}*{% endif %}</span>
                    </label>
                </div>
            {% elif field|widget_type == 'fileinput' or field|widget_type == 'clearablefileinput' %}
                {{ field }}
            {% else %}
                <label for="{{ field.id_for_label }}">
                    {{ field.label }}{% if field.field.required %} *{% endif %}
                </label>
                {% render_field field|add_class:"h-full-width" %}
            {% endif %}
            {% if field.errors %}
                <ul class="errorlist">
                    {% for error in field.errors %}
                        <li>
                            {{ error }}
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    {% endfor %}
</div>

website/diggers/templates/diggers/blocks/nav.html
{% url 'diggers:post_list' as post_list_url %}
{% url 'diggers:post_create' as post_create_url %}
{% url 'diggers:map_create' as map_create_url %}

{% url 'diggers:registration' as registration_url %}
{% url 'diggers:login' as login_url %}
{% url 'logout' as logout_url %}

<ul class="s-header__nav">
    <li {% if request.path == post_list_url %}class="current"{% endif %}><a href="{{ post_list_url }}">Блоґ</a></li>
    {% if request.user.is_authenticated and request.user.email_verified %}
        <li class="has-children {% if request.path == post_create_url or request.path == map_create_url %}current{% endif %}">
            <a href="#">Створити</a>
            <ul>
                <li><a href="{{ post_create_url }}">Пост</a></li>
                {% if request.user.is_authenticated and perms.diggers.hidden_access %}
                    <li><a href="{{ map_create_url }}">Мапу</a></li>
                {% endif %}
            </ul>
        </li>
    {% endif %}

    {% if not request.user.is_authenticated %}
        <li {% if request.path == login_url %}class="current"{% endif %}><a href="{{ login_url }}">Вхід</a></li>
        <li {% if request.path == registration_url %}class="current"{% endif %}><a href="{{ registration_url }}">Реєстрація</a>
        </li>
    {% else %}
        <li><a href="{% url 'diggers:profile' %}">Профайл</a></li>
        {% if request.user.is_staff %}
            <li><a href="{% url 'admin:index' %}">Адмінка</a></li>
        {% endif %}
        <li><a href="{{ logout_url }}?next={{ request.path }}">Вихід</a></li>
    {% endif %}
</ul> <!-- end #nav -->

website/diggers/templates/diggers/blocks/post_meta.html
{% load plural %}

<div class="entry__meta">
    <ul>
        {% if post.is_hidden %}
            <li><svg class="svg-inline--fa fa-lock fa-w-16" width="1792" height="1792" viewBox="0 0 1792 1792" aria-hidden="true" focusable="false" data-prefix="fa" data-icon="lock" role="img" xmlns="http://www.w3.org/2000/svg" data-fa-i2svg="">
                    <path d="M640 768h512v-192q0-106-75-181t-181-75-181 75-75 181v192zm832 96v576q0 40-28 68t-68 28h-960q-40 0-68-28t-28-68v-576q0-40 28-68t68-28h32v-192q0-184 132-316t316-132 316 132 132 316v192h32q40 0 68 28t28 68z"/>
                </svg><!--<i class="fa fa-lock" aria-hidden="true"></i>--></li>
        {% endif %}
        <li>{{ post.created_date }}</li>
        <li>
            {% if post.file %}
                <a href="{% url 'diggers:map_list' %}" title=""
                   rel="category tag">Мапи</a>
            {% else %}
                <a href="{% url 'diggers:list_by_category' category=post.category.route %}" title=""
                   rel="category tag">{{ post.category.name }}</a>
            {% endif %}
        </li>
        <li><a href="{% url 'diggers:list_by_author' post.author %}">{{ post.author }}</a></li>
        <li>{{ post.comment_set.all.count }} коментар{{ post.comment_set.all.count | plural:',я,ів' }}</li>
        {% if request.user.is_authenticated and post.author == request.user %}
            {% if perms.diggers.change_post %}
                <li><a href="{% url "diggers:post_update" post.pk %}" title="">Редагувати</a></li>
            {% endif %}

            {% if perms.diggers.delete_post %}
                <li><a href="{% url "diggers:post_delete" post.pk %}" title="">Видалити</a></li>
            {% endif %}
        {% endif %}
    </ul>
</div>

website/diggers/templates/diggers/blocks/profile.html
{% load static %}

<section>
    <h2 class="page-content__title">{% if author == request.user %}Мої пости{% else %}Пости користувача
        {{ author.username }}{% endif %}</h2>
    {% if author == request.user %}
        <div class="row">
            <div class="column large-full entry__meta">
                <ul>
                    <li><a href="{% url 'diggers:profile_update' %}">Змінити</a></li>
                    <li><a href="{% url 'password_change' %}">Змінити пароль</a></li>
                </ul>
            </div>
        </div>
    {% endif %}
    <div class="row">
        <div class="column large-3 lining">
            {% if author.avatar %}
                <img src="{{ MEDIA_URL }}{{ author.avatar }}" alt="avatar"/>
            {% else %}
                <img src="{% static "images/thumb.jpg" %}" alt="avatar"/>
            {% endif %}
        </div>
        <div class="column large-9 lining">
            <dl>
                <dt>Ім'я</dt>
                <dd>
                    {% if author.first_name or author.last_namme %}
                        {{ author.first_name }} {{ author.last_name }}
                    {% else %}
                        Не вказано
                    {% endif %}
                </dd>
                <dt> День народження</dt>
                <dd>{% if author.birth_date %}{{ author.birth_date }}{% else %}Не вказано{% endif %}</dd>
                <dt>Місцезнаходження</dt>
                <dd>{% if author.location %}{{ author.location }}{% else %}Не вказано{% endif %}</dd>
                <dt>Реєстрація</dt>
                <dd>{{ author.date_joined }}</dd>
                <dt>Був на сайті</dt>
                <dd>{% if author.last_activity %}{{ author.last_activity }}{% else %}Ніколи{% endif %}</dd>
            </dl>
        </div>
    </div>
</section>

website/diggers/templates/diggers/blocks/tagcloud.html
{% load tags %}

<div class="widget widget_tags">
    <h3 class="h6">Теги.</h3>

    <div class="tagcloud group">
        {% tags as cloud %}
        {% for tag in cloud %}
            <a href="{% url 'diggers:list_by_tags' tags=tag.name %}" class="tag-level-{{ tag.level }}">{{ tag.name }}</a>
        {% endfor %}
    </div>
</div>